console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = " "

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

#  [[blocks.segments]]
#    leading_diamond = ''
#    trailing_diamond = ''
#    template = ' {{ .OS }} '
#    foreground = '#ffffff'
#    background = '#c386f1'
#    type = 'session'
#    style = 'diamond'

  [[blocks.segments]]
    template = '   {{ .Path }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#ff479c'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_separator_icon = '  '
      home_icon = '~'
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#193549'
    powerline_symbol = ''
#background = '#fffb38'
    background = '#8438ff'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#6CA35E'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#8ED1F7'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#FFDE57'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    style = 'powerline'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']

    [blocks.segments.properties]
      display_default = false


[[tooltips]]
type = "gcp"
tips = [ "gcloud", "terragrunt", "terraform" ]
style = "plain"
foreground = "#e0af68"
template = "  {{.Project}} :: {{.Account}} "

[[tooltips]]
type = "go"
tips = [ "go" ]
style = "plain"
foreground = "#e0af68"
template = "  {{ .Full }} "

[[tooltips]]
type = "kubectl"
tips = [ "kubectl", "k" ]
style = "plain"
foreground = "#e0af68"
template = " 󱃾 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

